# Generated by Django 6.0.1 on 2026-03-29 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indisponibilidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indisponibilidade',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pendente'), ('APR', 'Aprovada'), ('REC', 'Recusada')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='indisponibilidade',
            name='motivo',
            field=models.CharField(choices=[('MED', 'Consulta médica'), ('FER', 'Férias'), ('CUR', 'Curso'), ('FOL', 'Folga'), ('OUT', 'Outro'), ('TACF', 'Tacf'), ('ESV', 'Entrando de serviço'), ('SSV', 'Saindo de servço'), ('DISP', 'Dispensa'), ('LIC', 'Licença'), ('COM', 'Comissão'), ('MIS', 'Missão')], max_length=5),
        ),
    ]
