# Generated by Django 6.0.1 on 2026-02-27 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaoescala',
            name='data',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='alocacaoescala',
            index=models.Index(fields=['data', 'usuario'], name='escalas_alo_data_c40135_idx'),
        ),
        migrations.AddConstraint(
            model_name='alocacaoescala',
            constraint=models.UniqueConstraint(fields=('usuario', 'data'), name='usuario_unico_por_dia'),
        ),
    ]
