# Generated by Django 6.0.1 on 2026-03-17 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0002_alocacaoescala_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alocacaoescala',
            name='pisteiro',
            field=models.BooleanField(default=False, help_text='Indica se o militar foi pisteiro no turno'),
        ),
    ]
