# Generated by Django 6.0.1 on 2026-03-24 01:20

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_precisa_trocar_senha'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telefone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
