# Generated by Django 6.0.1 on 2026-02-21 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0001_initial'),
        ('pontuacao', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='pontuacao',
            name='pontuacao_unica_por_alocacao',
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='escala',
            field=models.ForeignKey(blank=True, help_text='Opcional — útil para relatórios por semana', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to='escalas.escala'),
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='observacao',
            field=models.CharField(blank=True, help_text='Ex: falta, destaque, punição etc.', max_length=200),
        ),
        migrations.AlterField(
            model_name='pontuacao',
            name='alocacao',
            field=models.ForeignKey(blank=True, help_text='Opcional — usado se quiser pontuar automático', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pontuacoes', to='escalas.alocacaoescala'),
        ),
    ]
