# Generated by Django 6.0.1 on 2026-02-21 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pontuacao', '0002_remove_pontuacao_pontuacao_unica_por_alocacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontuacao',
            name='alocacao',
        ),
        migrations.RemoveField(
            model_name='pontuacao',
            name='escala',
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='tipo',
            field=models.CharField(blank=True, choices=[('PRETA', 'Preta (Dia útil)'), ('AMARELA', 'Amarela (Sexta)'), ('VERMELHA', 'Vermelha (Não útil)')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='pontuacao',
            name='observacao',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
