# Generated by Django 6.0.1 on 2026-02-21 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escalas', '0001_initial'),
        ('pontuacao', '0003_remove_pontuacao_alocacao_remove_pontuacao_escala_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontuacao',
            name='alocacao',
            field=models.ForeignKey(blank=True, help_text='Preenchido apenas se a pontuação veio da escala', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pontuacoes', to='escalas.alocacaoescala'),
        ),
        migrations.AddField(
            model_name='pontuacao',
            name='origem',
            field=models.CharField(blank=True, choices=[('ESC', 'Gerada pela Escala'), ('MAN', 'Lançamento Manual'), ('AJU', 'Ajuste Administrativo')], default='MAN', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='pontuacao',
            name='pontos',
            field=models.IntegerField(),
        ),
    ]
